name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      aidboxdb:
        image: healthsamurai/aidboxdb:17.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aidbox
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      aidbox:
        image: healthsamurai/aidboxone:latest
        env:
          AIDBOX_LICENSE: ${{ secrets.AIDBOX_LICENSE }}
          AIDBOX_CLIENT_ID: root
          AIDBOX_CLIENT_SECRET: secret
          AIDBOX_PORT: 8080
          AIDBOX_FHIR_VERSION: "4.0.1"
          BOX_PROJECT_VERSION: 1
          PGHOST: aidboxdb
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: aidbox
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl -f http://localhost:8080/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./... -run "^Test[^Acc]" -timeout 30s

      - name: Run acceptance tests
        env:
          TF_ACC: "1"
          AIDBOX_URL: "http://localhost:8080"
          AIDBOX_CLIENT_ID: "root"
          AIDBOX_CLIENT_SECRET: "secret"
        run: go test -v ./... -run "^TestAcc" -timeout 10m

      - name: Run vet
        run: go vet ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6" 
