name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      aidboxdb:
        image: healthsamurai/aidboxdb:17.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aidbox
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      aidbox:
        image: healthsamurai/aidboxone:latest
        env:
          AIDBOX_LICENSE: ${{ secrets.AIDBOX_LICENSE }}
          AIDBOX_CLIENT_ID: root
          AIDBOX_CLIENT_SECRET: secret
          AIDBOX_PORT: 8089
          AIDBOX_FHIR_VERSION: "4.0.1"
          BOX_PROJECT_VERSION: 1
          PGHOST: aidboxdb
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
          PGDATABASE: aidbox
        ports:
          - 8089:8089
        options: >-
          --health-cmd "curl -f http://localhost:8089/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Get dependencies
        run: |
          go mod download
          go mod verify

      - name: Wait for Aidbox to be ready
        run: |
          timeout 60s bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8089/health)" != "200" ]]; do sleep 5; done' || false

      - name: Run linters
        run: |
          go vet ./...
          go fmt ./...

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.6"

      - name: Run unit tests
        run: |
          go test -v ./... -run "^Test([^A]|A[^c]|Ac[^c])" -timeout 30s

      - name: Run resource tests
        run: |
          go test -v ./resources/... -timeout 30s

      - name: Run acceptance tests
        env:
          TF_ACC: "1"
          AIDBOX_URL: "http://localhost:8089"
          AIDBOX_CLIENT_ID: "root"
          AIDBOX_CLIENT_SECRET: "secret"
        run: |
          go test -v ./... -run "^TestAcc" -timeout 15m -parallel 1 